sudo: required
services:
 - docker

before_install:
 - docker build -t stevezmac/react-test -f ./client/Dockerfile.dev ./client

script:
 - docker run -e CI=true stevezmac/react-test npm run test -- --watchAll=false

after_success:
 - docker build -t stevezmac/multi-client ./client
 - docker build -t stevezmac/multi-nginx ./nginx
 - docker build -t stevezmac/multi-server ./server
 - docker build -t stevezmac/multi-worker ./worker
# log in to the docker CLI update ##
 - echo "$DOCKER_PWD" | docker login -u "$DOCKER_ID" --password-stdin
# take those images and push them to docker hub
 - docker push stevezmac/multi-client
 - docker push stevezmac/multi-nginx
 - docker push stevezmac/multi-server
 - docker push stevezmac/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-479832141322
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY



